# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
require_relative '../spm_dependencies_poc.rb'

target 'ObjCUIApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjCUIApp
  pod 'ObjCLib', path: '../ObjCLib'
end
