require_relative '../spm_dependencies_poc.rb'

platform :osx, '10.13'
target 'SwiftUIApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUIApp
  pod 'SwiftLib', path: '../SwiftLib'
end


